spring:
  cloud:
    gateway:
      server:
        webflux:
          routes[1]:
            id: clientes-microservice
            predicates[0]: Path=/clients/**
            uri: https://d2e34aeab101.ngrok-free.app/
          routes[0]:
            id: autos-microservice
            predicates[0]: Path=/api/auto/**
            uri: https://joellen-prebronze-undespondently.ngrok-free.dev/
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: '8080'
