spring:
  cloud:
    gateway:
      # ELIMINADO: server.webflux
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
      routes:
        - id: ms-cliente
          uri: lb://CLIENTS
          predicates:
            - Path=/api/clients/**
        - id: ms-autopartes
          uri: lb://AUTOPARTES
          predicates:
            - Path=/api/**
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: https://ms-eureka-server.nxgen.dev/eureka/
    register-with-eureka: true
    fetch-registry: true # Necesario para que el gateway encuentre los servicios

server:
  port: 8080
