spring:
  cloud:
    gateway:
      # ELIMINADO: server.webflux
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: ms-cliente
          uri: lb://CLIENTS
          predicates:
            - Path=/api/clients/**
        - id: ms-autopartes
          uri: lb://AUTOPARTES
          predicates:
            - Path=/api/**
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: https://ms-eureka-server.nxgen.dev/eureka/
    register-with-eureka: true
    fetch-registry: true # Necesario para que el gateway encuentre los servicios

server:
  port: 8080
