spring:
  datasource:
    url: jdbc:postgresql://pg-238b0340-ms-autoparts.h.aivencloud.com:22286/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_oei8lf3PxqAJE06o9PX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: false
  application:
    name: autopartes
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
logging:
  level:
    org:
      flywaydb: DEBUG
      
eureka:
  client:
    service-url:
      defaultZone: http://cc0cko8gscw08k8w0oocc000.46.62.225.65.sslip.io/eureka/
    register-with-eureka: true
    fetch-registry: true
