spring:
  datasource:
    url: jdbc:postgresql://avnadmin:AVNS_oei8lf3PxqAJE06o9PX@pg-238b0340-ms-autoparts.h.aivencloud.com:22286/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_oei8lf3PxqAJE06o9PX        # Solo el password correcto
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: clients
logging:
  level:
    org:
      flywaydb: DEBUG
      
eureka:
  client:
    service-url:
      defaultZone: https://eureka-server.vardocs.app/eureka/
    register-with-eureka: true
