spring:
  datasource:
    url: jdbc:mysql://localhost:3307/clients_db?createDatabaseIfNotExist=true
    username: root
    password: Zero.14789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org:
      flywaydb: DEBUG