spring:
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_x9b1KUgY_kO8PSPWw4W@db-clients-db-clients.f.aivencloud.com:16972/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_x9b1KUgY_kO8PSPWw4W
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: clients
logging:
  level:
    org:
      flywaydb: DEBUG
      
eureka:
  client:
    service-url:
      defaultZone: https://ms-eureka-server.nxgen.dev/eureka/
    register-with-eureka: true
