eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    service-url: 
      defaultZone: https://ms-eureka-server.nxgen.dev/eureka/
  instance: 
    hostname: ms-eureka-server.nxgen.dev 
    prefer-ip-address: false
    home-page-url: https://ms-eureka-server.nxgen.dev/ 
    status-page-url: https://ms-eureka-server.nxgen.dev/info 
    health-check-url: https://ms-eureka-server.nxgen.dev/health
spring:
  application:
    name: eureka-server
server:
  port: '8761'
